
version: 2

models:
    - name: my_first_dbt_model
      description: '{{ doc("table_events") }}'
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table. this is the second table"
            tests:
                - unique
                - not_null

    - name: example_team_details
      description: '{{doc("team_details_overview")}}'
      columns:
          - name: name
            description: '{{doc ("team_details_team_name")}}'
            tests:
              - not_null

          - name: city
            description: '{{doc ("team_details_team_city")}}'
            tests:
              - is_la_team

          - name: State
            description: '{{doc ("team_details_team_state")}}'
sources:
  - name: demo_db
    description: 'database im using for team locations'
    database: demo_db
    schema: PUBLIC
    tables:
      - name: team_locations
        description: 'Details nfl team name, city, and state'
